# Generated by Django 3.1 on 2020-08-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(upload_to='media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to='media/product_pics'),
        ),
    ]
