# Generated by Django 3.1 on 2020-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200827_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'PENDING'), ('f', 'FINISH'), ('c', 'CANCEL'), ('a', 'APPROVED')], default='p', max_length=1),
        ),
    ]
