# Generated by Django 3.1 on 2020-08-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200828_1350'),
        ('restaurant', '0003_auto_20200828_1315'),
    ]

    operations = [
    ]
